// src/components/ImportScreen.svelte
<script lang="ts">
  import { onMount } from "svelte";
  import { parseLayoutJson, buildValidLayout, filterLayout } from "../lib/layout";
  import { loadCSV, prepareDateLayout } from "../lib/duckdb";
  import { saveData, loadSaved } from "../lib/opfs";
  import { t } from "../lib/i18n.svelte";
  import {
    getSavedEntries,
    refreshSavedFiles,
    deleteSavedEntry,
  } from "../lib/savedFilesStore.svelte";

  import FileUploadPanel from "./import/FileUploadPanel.svelte";
  import SavedFiles from "./import/SavedFiles.svelte";
  import ValidationStep from "./import/ValidationStep.svelte";
  import Button from "./shared/Button.svelte";
  import SectionTitle from "./shared/SectionTitle.svelte";
  import Alert from "./shared/Alert.svelte";
  import type { RawData, LayoutData } from "../lib/types";
  import type { Layout } from "../lib/layout";

  interface Props {
    onComplete: (
      rawData: RawData,
      layout: LayoutData,
      dateWarnings: string[],
      preparedLayout: Layout,
    ) => void;
  }

  let { onComplete }: Props = $props();

  let rawData = $state<RawData | null>(null);
  let layout = $state<LayoutData | null>(null);
  let step = $state(1);
  let gsOpen = $state(false);
  let loadError = $state<string | null>(null);

  let loadedFromSaved = false;
  let opfsPayload: {
    rawDataText?: string;
    rawDataFileName?: string;
    layoutJson?: string;
    layoutFileName?: string;
  } = {};

  let entries = $derived(getSavedEntries());
  let bothLoaded = $derived(rawData !== null && layout !== null);
  let loadedInfo = $derived(
    rawData
      ? t("summary.rows", {
          rows: rawData.rowCount,
          cols: rawData.headers.length,
        })
      : null,
  );

  onMount(() => {
    void refreshSavedFiles();
  });

  const STEPS = [
    { num: 1, labelKey: "import.step.select" },
    { num: 2, labelKey: "import.step.validate" },
    { num: 3, labelKey: "import.step.proceed" },
  ] as const;

  async function handleRawDataFile(file: File) {
    try {
      loadError = null;
      const text = await file.text();
      const result = await loadCSV(text);
      opfsPayload = { ...opfsPayload, rawDataText: text, rawDataFileName: file.name };
      rawData = {
        fileName: file.name,
        headers: result.headers,
        rowCount: result.rowCount,
      };
      loadedFromSaved = false;
    } catch (e) {
      loadError = t("error.csv.load", { msg: (e as Error).message });
    }
  }

  async function handleLayoutFile(file: File) {
    try {
      loadError = null;
      const text = await file.text();
      const rawJson = parseLayoutJson(text);
      opfsPayload = { ...opfsPayload, layoutJson: text, layoutFileName: file.name };
      layout = { fileName: file.name, rawJson };
      loadedFromSaved = false;
    } catch (e) {
      loadError = t("error.layout.load", { msg: (e as Error).message });
    }
  }

  async function handleLoadFromSaved(folderId: string) {
    try {
      loadError = null;
      const data = await loadSaved(folderId);
      const rawJson = parseLayoutJson(data.layoutJson);
      const result = await loadCSV(data.rawDataText);

      opfsPayload = {
        rawDataText: data.rawDataText,
        rawDataFileName: data.rawDataName,
        layoutJson: data.layoutJson,
        layoutFileName: data.layoutName,
      };
      rawData = {
        fileName: data.rawDataName,
        headers: result.headers,
        rowCount: result.rowCount,
      };
      layout = { fileName: data.layoutName, rawJson };
      loadedFromSaved = true;
    } catch (e) {
      loadError = t("error.saved.load", { msg: (e as Error).message });
    }
  }

  function handleGoToValidation() {
    if (bothLoaded) step = 2;
  }

  function handleBackToUpload() {
    step = 1;
  }

  async function handleProceed() {
    if (!rawData || !layout) return;
    if (!loadedFromSaved && opfsPayload.rawDataText && opfsPayload.layoutJson) {
      try {
        await saveData(
          opfsPayload.rawDataFileName!,
          opfsPayload.rawDataText,
          opfsPayload.layoutFileName!,
          opfsPayload.layoutJson,
        );
        await refreshSavedFiles();
      } catch {
        // OPFS save is best-effort
      }
    }
    const validLayout = buildValidLayout(layout.rawJson);
    const filtered = filterLayout(rawData.headers, validLayout);
    const { layout: prepared, warnings } = await prepareDateLayout(filtered);
    onComplete(rawData, layout, warnings, prepared);
  }
</script>

{#snippet StepIndicator(currentStep: number)}
  <div class="mb-6 flex items-center justify-center gap-0">
    {#each STEPS as s, i (s.num)}
      {@const isDone = s.num < currentStep}
      {@const isActive = s.num === currentStep}
      <div class="flex items-center">
        {#if i > 0}
          <div
            class="mx-2 h-px w-8 transition-colors duration-300 {s.num <= currentStep
              ? 'bg-accent'
              : 'bg-border'}"
          ></div>
        {/if}
        <div class="flex items-center gap-2">
          <span
            class="flex h-7 w-7 items-center justify-center rounded-full text-xs font-bold transition-colors duration-300 {isDone
              ? 'bg-accent text-accent-contrast'
              : isActive
                ? 'border-2 border-accent bg-surface text-accent'
                : 'border-2 border-border bg-surface text-muted'}"
          >
            {isDone ? "\u2713" : s.num}
          </span>
          <span
            class="text-sm font-medium transition-colors duration-300 {isActive
              ? 'text-text'
              : isDone
                ? 'text-accent'
                : 'text-muted'}"
          >
            {t(s.labelKey)}
          </span>
        </div>
      </div>
    {/each}
  </div>
{/snippet}

<div class="flex items-center justify-center p-6">
  <div class="w-full max-w-[480px] rounded-xl border border-border bg-surface p-8 shadow-md">
    <h2 class="mb-5 text-xl font-bold text-text">{t("import.title")}</h2>

    {@render StepIndicator(step)}

    {#if step === 1}
      <FileUploadPanel
        rawDataFileName={rawData?.fileName ?? null}
        layoutFileName={layout?.fileName ?? null}
        onRawDataFile={handleRawDataFile}
        onLayoutFile={handleLayoutFile}
      />

      <div class="mt-5 border-t border-border pt-4">
        <SectionTitle>{t("import.history")}</SectionTitle>
        <div class="flex max-h-[160px] flex-col gap-2 overflow-y-auto">
          <SavedFiles
            {entries}
            onSelectEntry={handleLoadFromSaved}
            onDeleteEntry={deleteSavedEntry}
          />
        </div>
      </div>

      {#if loadedInfo}
        <Alert variant="info" role="status" class="mt-3 whitespace-pre-line">
          {loadedInfo}
        </Alert>
      {/if}

      {#if loadError}
        <Alert variant="error" class="mt-3">
          {loadError}
        </Alert>
      {/if}

      {#if bothLoaded}
        <div class="mt-5 w-full">
          <Button variant="primary" size="lg" onclick={handleGoToValidation}>
            {t("import.step.validate")} &rarr;
          </Button>
        </div>
      {/if}
    {:else if step === 2 && rawData && layout}
      <ValidationStep
        {rawData}
        {layout}
        onProceed={handleProceed}
        onBack={handleBackToUpload}
      />
    {/if}
  </div>

  <!-- Help Button -->
  <button
    class="fixed bottom-5 left-5 z-900 flex h-9 cursor-pointer items-center gap-1.5 rounded-full border-[1.5px] border-border-strong bg-surface px-3.5 text-sm font-semibold text-text-secondary shadow-[0_2px_8px_rgba(0,0,0,0.12)] transition-[background,color,transform] duration-150 hover:scale-[1.03] hover:border-[var(--color-primary-500)] hover:bg-[var(--color-primary-50)] hover:text-[var(--color-primary-700)]"
    aria-label={t("help.label")}
    onclick={() => (gsOpen = true)}
  >
    <span class="text-base leading-none">?</span>
    {t("help.button")}
  </button>

  <!-- Getting Started Modal -->
  {#if gsOpen}
    {#await import("./import/GettingStarted.svelte") then { default: GettingStartedModal }}
      <GettingStartedModal open={gsOpen} onClose={() => (gsOpen = false)} />
    {/await}
  {/if}
</div>

// src/components/screens/import/ImportScreen.tsx
import { useCallback, useRef, useState } from "preact/hooks";
import type { JSX } from "preact";
import { parseLayout, buildLayoutMeta } from "../../../lib/layout";
import { loadCSV } from "../../../lib/duckdbBridge";
import { saveData, loadSaved } from "../../../lib/opfs";
import { t } from "../../../lib/i18n";
import { Dropzone } from "./Dropzone";
import { SavedFilesList, triggerSavedFilesRefresh, useSavedFiles } from "../../leftPane/SavedFiles";
import type { CsvData, LayoutData } from "../../../lib/types";

type Tab = "file" | "saved";

interface ImportScreenProps {
  onComplete: (csv: CsvData, layout: LayoutData) => void;
}

const TABS: { key: Tab; labelKey: string }[] = [
  { key: "file", labelKey: "import.tab.file" },
  { key: "saved", labelKey: "import.tab.saved" },
];

export default function ImportScreen({ onComplete }: ImportScreenProps) {
  const [activeTab, setActiveTab] = useState<Tab>("file");
  const [csvFileName, setCsvFileName] = useState<string | null>(null);
  const [layoutFileName, setLayoutFileName] = useState<string | null>(null);
  const [showProceed, setShowProceed] = useState(false);
  const [loadedInfo, setLoadedInfo] = useState<string | null>(null);

  const tabRefs = useRef<(HTMLButtonElement | null)[]>([]);
  const csvRef = useRef<CsvData | null>(null);
  const layoutRef = useRef<LayoutData | null>(null);

  const { entries, deleteEntry } = useSavedFiles();

  function updateLoadedInfo(): void {
    const csv = csvRef.current;
    const layout = layoutRef.current;
    if (!csv && !layout) {
      setLoadedInfo(null);
      return;
    }
    const lines: string[] = [];
    if (csv) lines.push(csv.fileName);
    if (layout) lines.push(layout.fileName);
    if (csv) {
      lines.push(
        t("summary.rows", {
          rows: csv.rowCount.toLocaleString(),
          cols: csv.headers.length,
        }),
      );
    }
    setLoadedInfo(lines.join("\n"));
  }

  function checkBothLoaded(): void {
    if (!csvRef.current || !layoutRef.current) return;
    setShowProceed(true);
    updateLoadedInfo();
  }

  async function trySaveToOPFS(): Promise<void> {
    const csv = csvRef.current;
    const layout = layoutRef.current;
    if (!csv || !layout) return;
    try {
      await saveData(csv.fileName, csv.text, layout.fileName, layout.json);
      triggerSavedFilesRefresh();
    } catch (e) {
      console.warn("OPFS save failed:", e);
    }
  }

  const handleCsvFile = useCallback(async (file: File) => {
    try {
      const text = await file.text();
      const result = await loadCSV(text);
      csvRef.current = {
        text,
        fileName: file.name,
        headers: result.headers,
        rowCount: result.rowCount,
      };
      setCsvFileName(file.name);
      updateLoadedInfo();
      checkBothLoaded();
      trySaveToOPFS();
    } catch (e) {
      console.error("CSV load failed:", e);
    }
  }, []);

  const handleLayoutFile = useCallback(async (file: File) => {
    try {
      const text = await file.text();
      const layout = parseLayout(text);
      const meta = buildLayoutMeta(layout);
      layoutRef.current = { json: text, fileName: file.name, meta };
      setLayoutFileName(file.name);
      updateLoadedInfo();
      checkBothLoaded();
      trySaveToOPFS();
    } catch (e) {
      console.error("Layout load failed:", e);
    }
  }, []);

  const handleLoadFromSaved = useCallback(async (folderId: string) => {
    try {
      const { csvText, csvName, layoutJson, layoutName } = await loadSaved(folderId);
      const layout = parseLayout(layoutJson);
      const meta = buildLayoutMeta(layout);
      const result = await loadCSV(csvText);

      csvRef.current = {
        text: csvText,
        fileName: csvName,
        headers: result.headers,
        rowCount: result.rowCount,
      };
      layoutRef.current = { json: layoutJson, fileName: layoutName, meta };

      setCsvFileName(csvName);
      setLayoutFileName(layoutName);
      updateLoadedInfo();
      checkBothLoaded();
    } catch (e) {
      console.error("Saved data load failed:", e);
    }
  }, []);

  function handleProceed(): void {
    if (csvRef.current && layoutRef.current) {
      onComplete(csvRef.current, layoutRef.current);
    }
  }

  function activateTab(idx: number) {
    setActiveTab(TABS[idx].key);
    tabRefs.current[idx]?.focus();
  }

  function handleTabKeyDown(e: JSX.TargetedKeyboardEvent<HTMLButtonElement>, idx: number) {
    const len = TABS.length;
    if (e.key === "ArrowRight" || e.key === "ArrowDown") {
      e.preventDefault();
      activateTab((idx + 1) % len);
    } else if (e.key === "ArrowLeft" || e.key === "ArrowUp") {
      e.preventDefault();
      activateTab((idx - 1 + len) % len);
    } else if (e.key === "Home") {
      e.preventDefault();
      activateTab(0);
    } else if (e.key === "End") {
      e.preventDefault();
      activateTab(len - 1);
    }
  }

  return (
    <div class="flex items-center justify-center p-6">
      <div class="w-full max-w-[480px] rounded-xl border border-border bg-surface p-8 shadow-md">
        <h2 class="mb-5 text-xl font-bold text-text">{t("import.title")}</h2>

        {/* Tabs */}
        <div class="mb-3 flex" role="tablist" aria-label={t("import.tab.label")}>
          {TABS.map((tab, i) => {
            const isActive = activeTab === tab.key;
            return (
              <button
                key={tab.key}
                ref={(el) => {
                  tabRefs.current[i] = el;
                }}
                class="flex-1 cursor-pointer border border-border bg-surface px-0 py-2 text-[0.875rem] font-medium text-text-secondary transition-[background,color,border-color] duration-150 first:rounded-l-sm last:rounded-r-sm last:border-l-0 data-[active=true]:border-accent data-[active=true]:bg-accent data-[active=true]:text-accent-contrast"
                role="tab"
                aria-selected={isActive}
                aria-controls={`tab-${tab.key}`}
                data-active={String(isActive)}
                tabIndex={isActive ? 0 : -1}
                onClick={() => setActiveTab(tab.key)}
                onKeyDown={(e) => handleTabKeyDown(e, i)}
              >
                {t(tab.labelKey)}
              </button>
            );
          })}
        </div>

        {/* File Tab */}
        <div
          class={`h-[250px] overflow-y-auto${activeTab !== "file" ? " hidden" : ""}`}
          id="tab-file"
          role="tabpanel"
          aria-labelledby="tab-btn-file"
        >
          <Dropzone
            accept=".csv"
            icon={t("dropzone.csv.icon")}
            text={t("dropzone.csv.text")}
            hint={t("dropzone.csv.hint")}
            loadedFileName={csvFileName}
            onFile={handleCsvFile}
          />
          <div class="mt-3">
            <Dropzone
              accept=".json"
              icon={t("dropzone.layout.icon")}
              text={t("dropzone.layout.text")}
              hint={t("dropzone.layout.hint")}
              loadedFileName={layoutFileName}
              onFile={handleLayoutFile}
            />
          </div>
        </div>

        {/* Saved Tab */}
        <div
          class={`h-[250px] overflow-y-auto${activeTab !== "saved" ? " hidden" : ""}`}
          id="tab-saved"
          role="tabpanel"
          aria-labelledby="tab-btn-saved"
        >
          <div class="flex flex-col gap-2">
            <SavedFilesList
              entries={entries}
              onSelectEntry={handleLoadFromSaved}
              onDeleteEntry={deleteEntry}
            />
          </div>
        </div>

        {/* Loaded data info */}
        {loadedInfo && (
          <div
            class="mt-3 whitespace-pre-line rounded-lg border border-accent-light bg-accent-bg px-4 py-3 text-[0.875rem] leading-normal text-text-secondary"
            aria-live="polite"
          >
            {loadedInfo}
          </div>
        )}

        {/* Proceed button */}
        {showProceed && (
          <button
            class="mt-5 min-h-12 w-full cursor-pointer rounded-lg border-none bg-accent px-4 py-3 text-base font-bold tracking-[0.02em] text-accent-contrast transition-[background] duration-150 hover:bg-accent-hover active:bg-[var(--color-primary-900)]"
            onClick={handleProceed}
          >
            {t("import.proceed")}
          </button>
        )}
      </div>
    </div>
  );
}
