// src/components/leftPane/SavedFiles.tsx
import { render } from "preact";
import { listSaved, deleteSaved } from "../../lib/opfs";
import { t } from "../../lib/i18n";

type OnSelectCallback = (folderId: string) => void;

let onSelect: OnSelectCallback = () => {};

interface SavedEntry {
  folderId: string;
  csvName: string;
  timestamp: number;
}

function SavedFilesList({
  entries,
  onSelectEntry,
}: {
  entries: SavedEntry[];
  onSelectEntry: OnSelectCallback;
}) {
  if (entries.length === 0) {
    return <div class="p-4 text-center text-[0.875rem] text-muted">{t("saved.empty")}</div>;
  }

  return (
    <>
      {entries.map((entry) => {
        const date = new Date(entry.timestamp);
        const dateStr = `${date.getMonth() + 1}/${date.getDate()} ${date.getHours()}:${String(date.getMinutes()).padStart(2, "0")}`;

        return (
          <div
            key={entry.folderId}
            class="flex items-center gap-2 rounded-lg border border-transparent bg-surface2 transition-[border-color] duration-150 hover:border-border-strong"
          >
            <button
              class="min-h-11 flex-1 cursor-pointer overflow-hidden text-ellipsis whitespace-nowrap border-none bg-transparent px-4 py-3 text-left text-[0.875rem] text-text hover:text-accent"
              type="button"
              onClick={() => onSelectEntry(entry.folderId)}
            >
              {entry.csvName} ({dateStr})
            </button>
            <button
              class="flex min-h-11 min-w-11 shrink-0 cursor-pointer items-center justify-center border-none bg-transparent px-3 py-2 text-[0.875rem] text-muted transition-[color] duration-150 hover:text-danger"
              type="button"
              aria-label={t("saved.delete", { name: entry.csvName })}
              onClick={async (e) => {
                e.stopPropagation();
                await deleteSaved(entry.folderId);
                refreshList();
              }}
            >
              ×
            </button>
          </div>
        );
      })}
    </>
  );
}

export function initSavedFiles(onSelectCb: OnSelectCallback): void {
  onSelect = onSelectCb;
  refreshList();
}

export async function refreshList(): Promise<void> {
  const container = document.getElementById("saved-files-list")!;

  let entries: SavedEntry[];
  try {
    entries = await listSaved();
  } catch {
    render(<></>, container);
    return;
  }

  render(<SavedFilesList entries={entries} onSelectEntry={onSelect} />, container);
}

// apps/desktop/src/components/import/SavedFiles.svelte
<script lang="ts">
  import type { SavedEntry } from "@aggy/lib";
  import { t } from "@aggy/ui";

  interface Props {
    entries: SavedEntry[];
    onSelectEntry: (folderId: string) => void;
    onDeleteEntry: (folderId: string) => void;
  }

  let { entries, onSelectEntry, onDeleteEntry }: Props = $props();
</script>

{#if entries.length === 0}
  <div class="p-4 text-center text-sm text-muted">{t("saved.empty")}</div>
{:else}
  {#each entries as entry (entry.folderId)}
    {@const date = new Date(entry.timestamp)}
    {@const dateStr = `${date.getMonth() + 1}/${date.getDate()} ${date.getHours()}:${String(date.getMinutes()).padStart(2, "0")}`}
    <div
      class="flex items-center gap-2 rounded-lg border border-transparent bg-surface2 transition-colors hover:border-border-strong"
    >
      <button
        class="min-h-11 flex-1 cursor-pointer overflow-hidden text-ellipsis whitespace-nowrap px-4 py-3 text-left text-sm text-text hover:text-accent"
        type="button"
        onclick={() => onSelectEntry(entry.folderId)}
      >
        {entry.rawDataName} ({dateStr})
      </button>
      <button
        class="flex min-h-11 min-w-11 shrink-0 cursor-pointer items-center justify-center px-3 py-2 text-sm text-muted transition-colors hover:text-danger"
        type="button"
        aria-label={t("saved.delete", { name: entry.rawDataName })}
        onclick={(e: MouseEvent) => {
          e.stopPropagation();
          onDeleteEntry(entry.folderId);
        }}
      >
        &times;
      </button>
    </div>
  {/each}
{/if}
