// src/components/AggregationScreen.svelte
<script lang="ts">
  import { onMount } from "svelte";
  import type { RawData, LayoutData, Tab } from "../lib/types";
  import ResultPanel from "./aggregation/ResultPanel.svelte";
  import SettingsPanel from "./aggregation/SettingsPanel.svelte";
  import { runAggregation } from "../lib/duckdb.svelte";
  import type { Layout } from "../lib/layout";
  import { buildQuestions, findWeightColumn } from "../lib/layout";
  import { t } from "../lib/i18n.svelte";

  interface Props {
    rawData: RawData;
    layout: LayoutData;
    preparedLayout: Layout;
    dateWarnings: string[];
  }

  let { rawData, layout, preparedLayout, dateWarnings }: Props = $props();

  let questions = $derived(buildQuestions(preparedLayout));
  let weightCol = $derived(findWeightColumn(preparedLayout));

  let crossSelected = $state<Record<string, boolean>>({});
  let weightEnabled = $state(true);
  let errorMsg = $state("");
  let aggResult = $state<{ tabs: Tab[]; weightCol: string } | null>(null);

  // Initialize crossSelected when questions change
  $effect(() => {
    const sel: Record<string, boolean> = {};
    for (const q of questions) sel[q.code] = false;
    crossSelected = sel;
  });

  async function handleRunAggregation(): Promise<void> {
    errorMsg = "";
    const activeWeightCol = weightEnabled ? weightCol : "";
    const crossQuestions = questions.filter((q) => crossSelected[q.code]);

    try {
      const tabs = await runAggregation(questions, crossQuestions, activeWeightCol);
      aggResult = { tabs, weightCol: activeWeightCol };
    } catch (e) {
      errorMsg = t("error.aggregation", { msg: (e as Error).message });
    }
  }

  // Run aggregation once on mount
  onMount(() => {
    void handleRunAggregation();
  });
</script>

<SettingsPanel
  {rawData}
  {layout}
  {preparedLayout}
  {questions}
  {crossSelected}
  onCrossToggle={(key, checked) => (crossSelected = { ...crossSelected, [key]: checked })}
  {weightCol}
  {weightEnabled}
  onWeightToggle={(on) => (weightEnabled = on)}
  {dateWarnings}
  {errorMsg}
  onRun={() => handleRunAggregation()}
/>

<ResultPanel tabs={aggResult?.tabs ?? null} weightCol={aggResult?.weightCol ?? ""} />

// src/components/AggregationScreen.tsx
import { useEffect, useState } from "preact/hooks";
import type { Tab } from "../lib/agg/types";
import ResultPanel from "./aggregation/ResultPanel";
import SettingsPanel from "./aggregation/SettingsPanel";
import { runAggregation } from "../lib/duckdb";
import type { Layout } from "../lib/layout";
import { buildQuestions, findWeightColumn } from "../lib/layout";
import { t } from "../lib/i18n";
import type { RawData, LayoutData } from "../lib/types";

interface AggregationScreenProps {
  rawData: RawData;
  layout: LayoutData;
  preparedLayout: Layout;
  dateWarnings: string[];
}

export default function AggregationScreen({
  rawData,
  layout,
  preparedLayout,
  dateWarnings,
}: AggregationScreenProps) {
  const questions = buildQuestions(preparedLayout);
  const weightCol = findWeightColumn(preparedLayout);

  const [crossSelected, setCrossSelected] = useState<Record<string, boolean>>(() => {
    const sel: Record<string, boolean> = {};
    questions.forEach((q) => (sel[q.code] = false));
    return sel;
  });
  const [weightEnabled, setWeightEnabled] = useState(true);
  const [errorMsg, setErrorMsg] = useState("");
  const [aggResult, setAggResult] = useState<{ tabs: Tab[]; weightCol: string } | null>(null);

  // Run aggregation once on mount
  useEffect(() => {
    handleRunAggregation();
  }, []);

  async function handleRunAggregation(): Promise<void> {
    setErrorMsg("");

    const activeWeightCol = weightEnabled ? weightCol : "";
    const crossQuestions = questions.filter((q) => crossSelected[q.code]);

    try {
      const tabs = await runAggregation(questions, crossQuestions, activeWeightCol);
      setAggResult({ tabs, weightCol: activeWeightCol });
    } catch (e) {
      setErrorMsg(t("error.aggregation", { msg: (e as Error).message }));
    }
  }

  return (
    <>
      <SettingsPanel
        rawData={rawData}
        layout={layout}
        preparedLayout={preparedLayout}
        questions={questions}
        crossSelected={crossSelected}
        onCrossToggle={(key, checked) => setCrossSelected((prev) => ({ ...prev, [key]: checked }))}
        weightCol={weightCol}
        weightEnabled={weightEnabled}
        onWeightToggle={setWeightEnabled}
        dateWarnings={dateWarnings}
        errorMsg={errorMsg}
        onRun={() => handleRunAggregation()}
      />

      <ResultPanel tabs={aggResult?.tabs ?? null} weightCol={aggResult?.weightCol ?? ""} />
    </>
  );
}
