// apps/desktop/src/App.svelte
<script lang="ts">
  import "./tailwind.css";
  import { onMount } from "svelte";
  import { initTheme } from "@aggy/ui";
  import { initDuckDB } from "./lib/duckdb";
  import Header from "./components/Header.svelte";
  import ImportScreen from "./components/ImportScreen.svelte";
  import AggregationScreen from "./components/AggregationScreen.svelte";
  import type { Layout, RawData, LayoutData } from "@aggy/lib";

  let screen = $state<"import" | "aggregation">("import");
  let loadedData = $state<{
    rawData: RawData;
    layout: LayoutData;
    preparedLayout: Layout;
    dateWarnings: string[];
  } | null>(null);

  let isImport = $derived(screen === "import");

  function handleComplete(
    rawData: RawData,
    layout: LayoutData,
    dateWarnings: string[],
    preparedLayout: Layout,
  ) {
    loadedData = { rawData, layout, preparedLayout, dateWarnings };
    screen = "aggregation";
  }

  onMount(() => {
    initTheme();
    initDuckDB().catch(() => {});
  });
</script>

<div class="flex h-screen flex-col overflow-hidden">
  <Header {isImport} onBack={() => (screen = "import")} />

  <main
    class="grid min-h-0 flex-1 grid-rows-1"
    style:grid-template-columns={isImport ? "1fr" : "360px 1fr"}
  >
    {#if isImport}
      <ImportScreen onComplete={handleComplete} />
    {:else if loadedData}
      <AggregationScreen
        rawData={loadedData.rawData}
        layout={loadedData.layout}
        preparedLayout={loadedData.preparedLayout}
        dateWarnings={loadedData.dateWarnings}
      />
    {/if}
  </main>
</div>

// src/App.tsx
import { useCallback, useEffect, useState } from "preact/hooks";
import { initDuckDB } from "./lib/duckdb";
import { initTheme } from "./components/header/SettingsModal";
import Header from "./components/Header";
import ImportScreen from "./components/ImportScreen";
import AggregationScreen from "./components/AggregationScreen";
import { onLocaleChange } from "./lib/i18n";
import type { Layout } from "./lib/layout";
import type { RawData, LayoutData } from "./lib/types";

export default function App() {
  const [screen, setScreen] = useState<"import" | "aggregation">("import");
  const [, setTick] = useState(0);
  const [loadedData, setLoadedData] = useState<{
    rawData: RawData;
    layout: LayoutData;
    preparedLayout: Layout;
    dateWarnings: string[];
  } | null>(null);
  const isImport = screen === "import";

  // Re-render on locale change
  useEffect(() => {
    onLocaleChange(() => setTick((n) => n + 1));
  }, []);

  const handleComplete = useCallback(
    (rawData: RawData, layout: LayoutData, dateWarnings: string[], preparedLayout: Layout) => {
      setLoadedData({ rawData, layout, preparedLayout, dateWarnings });
      setScreen("aggregation");
    },
    [],
  );

  // Imperative initialization (runs once after mount)
  useEffect(() => {
    initTheme();
    initDuckDB().catch(() => {});
  }, []);

  return (
    <div class="flex h-screen flex-col overflow-hidden">
      <Header isImport={isImport} onBack={() => setScreen("import")} />

      {/* Main */}
      <main
        class="grid min-h-0 flex-1 grid-rows-1"
        style={{ gridTemplateColumns: isImport ? "1fr" : "360px 1fr" }}
      >
        {isImport ? (
          <ImportScreen onComplete={handleComplete} />
        ) : (
          loadedData && (
            <AggregationScreen
              rawData={loadedData.rawData}
              layout={loadedData.layout}
              preparedLayout={loadedData.preparedLayout}
              dateWarnings={loadedData.dateWarnings}
            />
          )
        )}
      </main>
    </div>
  );
}
